# Generated by Django 4.1.3 on 2022-11-25 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marque", models.CharField(max_length=150)),
                ("modele", models.CharField(max_length=150)),
                ("kilometrage", models.FloatField()),
                ("prix_journalier", models.FloatField()),
                (
                    "conducteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
