# Generated by Django 4.1.3 on 2022-11-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_vehicule"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicule",
            name="est_loue",
            field=models.BooleanField(default=False),
        ),
    ]
